// Code generated by templ - DO NOT EDIT.

package onlyscripts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	templ "github.com/senforsce/tndr"
	templruntime "github.com/senforsce/tndr/runtime"
)

func withParameters(a string, b string, c int) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_withParameters_1056`,
		Function: `function __templ_withParameters_1056(a, b, c){console.log(a, b, c);
}`,
		Call:       templ.SafeScript(`__templ_withParameters_1056`, a, b, c),
		CallInline: templ.SafeScriptInline(`__templ_withParameters_1056`, a, b, c),
	}
}

var _ = templruntime.GeneratedTemplate
