// Code generated by Tndr(t1) - DO NOT EDIT.

// Tndr(t1): version: v0.0.3

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "github.com/senforsce/o/tr"
import "context"
import "io"
import "bytes"
import "strings"

import "strconv"

func border() t1.CSSClass {
	var t1_7745c5c3_CSSBuilder strings.Builder
	t1_7745c5c3_CSSBuilder.WriteString(`border:1px solid #eeeeee;`)
	t1_7745c5c3_CSSBuilder.WriteString(`border-radius:4px;`)
	t1_7745c5c3_CSSBuilder.WriteString(`margin:10px;`)
	t1_7745c5c3_CSSBuilder.WriteString(`padding-top:30px;`)
	t1_7745c5c3_CSSBuilder.WriteString(`padding-bottom:30px;`)
	t1_7745c5c3_CSSID := t1.CSSID(`border`, t1_7745c5c3_CSSBuilder.String())
	return t1.ComponentCSSClass{
		ID:    t1_7745c5c3_CSSID,
		Class: t1.SafeCSS(`.` + t1_7745c5c3_CSSID + `{` + t1_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func counts(global, session int) t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<form id=" + tr.Echo("countsForm") + " action=" + tr.Echo("/") + " method=" + tr.Echo("POST") + " hx-post=" + tr.Echo("/") + " hx-select=" + tr.Echo("#countsForm") + " hx-swap=" + tr.Echo("outerHTML") + "><div class=" + tr.Echo("columns") + ">")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var2 = []any{"column", "has-text-centered", "is-primary", border}
		t1_7745c5c3_Err = t1.RenderCSSItems(ctx, t1_7745c5c3_Buffer, t1_7745c5c3_Var2...)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<div class=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1.CSSClasses(t1_7745c5c3_Var2).String()))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\"><h1 class=" + tr.Echo("title is-size-1 has-text-centered") + ">")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var3 string
		t1_7745c5c3_Var3, t1_7745c5c3_Err = t1.JoinStringErrs(strconv.Itoa(global))
		if t1_7745c5c3_Err != nil {
			return t1.Error{Err: t1_7745c5c3_Err, FileName: `examples/counter/components/components.t1`, Line: 16, Col: 72}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var3))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</h1><p class=" + tr.Echo("subtitle has-text-centered") + ">Global</p><div><button class=" + tr.Echo("button is-primary") + " type=" + tr.Echo("submit") + " name=" + tr.Echo("global") + " value=" + tr.Echo("global") + ">+1</button></div></div>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var4 = []any{"column", "has-text-centered", border}
		t1_7745c5c3_Err = t1.RenderCSSItems(ctx, t1_7745c5c3_Buffer, t1_7745c5c3_Var4...)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<div class=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1.CSSClasses(t1_7745c5c3_Var4).String()))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\"><h1 class=" + tr.Echo("title is-size-1 has-text-centered") + ">")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var5 string
		t1_7745c5c3_Var5, t1_7745c5c3_Err = t1.JoinStringErrs(strconv.Itoa(session))
		if t1_7745c5c3_Err != nil {
			return t1.Error{Err: t1_7745c5c3_Err, FileName: `examples/counter/components/components.t1`, Line: 21, Col: 73}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var5))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</h1><p class=" + tr.Echo("subtitle has-text-centered") + ">Session</p><div><button class=" + tr.Echo("button is-secondary") + " type=" + tr.Echo("submit") + " name=" + tr.Echo("session") + " value=" + tr.Echo("session") + ">+1</button></div></div></div></form>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}

func Page(global, session int) t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var6 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var6 == nil {
			t1_7745c5c3_Var6 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<html><head><meta charset=" + tr.Echo("UTF-8") + "><meta name=" + tr.Echo("viewport") + " content=" + tr.Echo("width=device-width, initial-scale=1.0") + "><title>Counts</title><link rel=" + tr.Echo("stylesheet") + " href=" + tr.Echo("/assets/css/bulma.min.css") + "><link rel=" + tr.Echo("apple-touch-icon") + " sizes=" + tr.Echo("180x180") + " href=" + tr.Echo("/assets/favicon/apple-touch-icon.png") + "><link rel=" + tr.Echo("icon") + " type=" + tr.Echo("image/png") + " sizes=" + tr.Echo("32x32") + " href=" + tr.Echo("/assets/favicon/favicon-32x32.png") + "><link rel=" + tr.Echo("icon") + " type=" + tr.Echo("image/png") + " sizes=" + tr.Echo("16x16") + " href=" + tr.Echo("/assets/favicon/favicon-16x16.png") + "><link rel=" + tr.Echo("manifest") + " href=" + tr.Echo("/assets/favicon/site.webmanifest") + "><script src=" + tr.Echo("/assets/js/htmx.min.js") + "></script></head><body class=" + tr.Echo("bg-gray-100") + "><header class=" + tr.Echo("hero is-primary") + "><div class=" + tr.Echo("hero-body") + "><div class=" + tr.Echo("container") + "><h1 class=" + tr.Echo("title") + ">Counts</h1></div></div></header><section class=" + tr.Echo("section") + "><div class=" + tr.Echo("container") + "><div class=" + tr.Echo("columns is-centered") + "><div class=" + tr.Echo("column is-half") + ">")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = counts(global, session).Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</div></div></div></section></body></html>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}
