// Code generated by tndr - DO NOT EDIT.

// tndr: version: v0.1.0

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "github.com/senforsce/o/tr"
import tndrruntime "github.com/senforsce/tndr/runtime"

func RemoteInclusionTest() tndr.Component {
	return tndrruntime.GeneratedTemplate(func(tndr_7745c5c3_Input tndrruntime.GeneratedComponentInput) (tndr_7745c5c3_Err error) {
		tndr_7745c5c3_W, ctx := tndr_7745c5c3_Input.Writer, tndr_7745c5c3_Input.Context
		if tndr_7745c5c3_CtxErr := ctx.Err(); tndr_7745c5c3_CtxErr != nil {
			return tndr_7745c5c3_CtxErr
		}
		tndr_7745c5c3_Buffer, tndr_7745c5c3_IsBuffer := tndrruntime.GetBuffer(tndr_7745c5c3_W)
		if !tndr_7745c5c3_IsBuffer {
			defer func() {
				tndr_7745c5c3_BufErr := tndrruntime.ReleaseBuffer(tndr_7745c5c3_Buffer)
				if tndr_7745c5c3_Err == nil {
					tndr_7745c5c3_Err = tndr_7745c5c3_BufErr
				}
			}()
		}
		ctx = tndr.InitializeContext(ctx)
		tndr_7745c5c3_Var1 := tndr.GetChildren(ctx)
		if tndr_7745c5c3_Var1 == nil {
			tndr_7745c5c3_Var1 = tndr.NopComponent
		}
		ctx = tndr.ClearChildren(ctx)
		tndr_7745c5c3_Err = Remote.Render(ctx, tndr_7745c5c3_Buffer)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		return nil
	})
}

func Remote2() tndr.Component {
	return tndrruntime.GeneratedTemplate(func(tndr_7745c5c3_Input tndrruntime.GeneratedComponentInput) (tndr_7745c5c3_Err error) {
		tndr_7745c5c3_W, ctx := tndr_7745c5c3_Input.Writer, tndr_7745c5c3_Input.Context
		if tndr_7745c5c3_CtxErr := ctx.Err(); tndr_7745c5c3_CtxErr != nil {
			return tndr_7745c5c3_CtxErr
		}
		tndr_7745c5c3_Buffer, tndr_7745c5c3_IsBuffer := tndrruntime.GetBuffer(tndr_7745c5c3_W)
		if !tndr_7745c5c3_IsBuffer {
			defer func() {
				tndr_7745c5c3_BufErr := tndrruntime.ReleaseBuffer(tndr_7745c5c3_Buffer)
				if tndr_7745c5c3_Err == nil {
					tndr_7745c5c3_Err = tndr_7745c5c3_BufErr
				}
			}()
		}
		ctx = tndr.InitializeContext(ctx)
		tndr_7745c5c3_Var2 := tndr.GetChildren(ctx)
		if tndr_7745c5c3_Var2 == nil {
			tndr_7745c5c3_Var2 = tndr.NopComponent
		}
		ctx = tndr.ClearChildren(ctx)
		tndr_7745c5c3_Err = Remote.Render(ctx, tndr_7745c5c3_Buffer)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		return nil
	})
}

var _ = tndrruntime.GeneratedTemplate
