// Code generated by tndr - DO NOT EDIT.

// tndr: version: v0.1.0

package httpdebug

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "github.com/senforsce/o/tr"
import tndrruntime "github.com/senforsce/tndr/runtime"

func list(uris []string) tndr.Component {
	return tndrruntime.GeneratedTemplate(func(tndr_7745c5c3_Input tndrruntime.GeneratedComponentInput) (tndr_7745c5c3_Err error) {
		tndr_7745c5c3_W, ctx := tndr_7745c5c3_Input.Writer, tndr_7745c5c3_Input.Context
		if tndr_7745c5c3_CtxErr := ctx.Err(); tndr_7745c5c3_CtxErr != nil {
			return tndr_7745c5c3_CtxErr
		}
		tndr_7745c5c3_Buffer, tndr_7745c5c3_IsBuffer := tndrruntime.GetBuffer(tndr_7745c5c3_W)
		if !tndr_7745c5c3_IsBuffer {
			defer func() {
				tndr_7745c5c3_BufErr := tndrruntime.ReleaseBuffer(tndr_7745c5c3_Buffer)
				if tndr_7745c5c3_Err == nil {
					tndr_7745c5c3_Err = tndr_7745c5c3_BufErr
				}
			}()
		}
		ctx = tndr.InitializeContext(ctx)
		tndr_7745c5c3_Var1 := tndr.GetChildren(ctx)
		if tndr_7745c5c3_Var1 == nil {
			tndr_7745c5c3_Var1 = tndr.NopComponent
		}
		ctx = tndr.ClearChildren(ctx)
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 1, "<table><tr><th>File</th><th></th><th></th><th></th><th></th></tr>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		for _, uri := range uris {
			tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 2, "<tr class=\"test\"><td>")
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			var tndr_7745c5c3_Var2 string
			tndr_7745c5c3_Var2, tndr_7745c5c3_Err = tndr.JoinStringErrs(uri)
			if tndr_7745c5c3_Err != nil {
				return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/lspcmd/httpdebug/list.t1`), Line: 14, Col: 13}
			}
			_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var2))
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 3, "</td><td><a href=\"")
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			var tndr_7745c5c3_Var3 tndr.SafeURL
			tndr_7745c5c3_Var3, tndr_7745c5c3_Err = tndr.JoinURLErrs(getMapURL(uri))
			if tndr_7745c5c3_Err != nil {
				return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/lspcmd/httpdebug/list.t1`), Line: 15, Col: 32}
			}
			_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var3))
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 4, "\">Mapping</a></td><td><a href=\"")
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			var tndr_7745c5c3_Var4 tndr.SafeURL
			tndr_7745c5c3_Var4, tndr_7745c5c3_Err = tndr.JoinURLErrs(getSourceMapURL(uri))
			if tndr_7745c5c3_Err != nil {
				return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/lspcmd/httpdebug/list.t1`), Line: 16, Col: 38}
			}
			_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var4))
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 5, "\">Source Map</a></td><td><a href=\"")
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			var tndr_7745c5c3_Var5 tndr.SafeURL
			tndr_7745c5c3_Var5, tndr_7745c5c3_Err = tndr.JoinURLErrs(getTndrURL(uri))
			if tndr_7745c5c3_Err != nil {
				return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/lspcmd/httpdebug/list.t1`), Line: 17, Col: 33}
			}
			_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var5))
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 6, "\">Tndr</a></td><td><a href=\"")
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			var tndr_7745c5c3_Var6 tndr.SafeURL
			tndr_7745c5c3_Var6, tndr_7745c5c3_Err = tndr.JoinURLErrs(getGoURL(uri))
			if tndr_7745c5c3_Err != nil {
				return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/lspcmd/httpdebug/list.t1`), Line: 18, Col: 31}
			}
			_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var6))
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
			tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 7, "\">Go</a></td></tr>")
			if tndr_7745c5c3_Err != nil {
				return tndr_7745c5c3_Err
			}
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 8, "</table>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		return nil
	})
}

var _ = tndrruntime.GeneratedTemplate
