// Code generated by tndr - DO NOT EDIT.

// tndr: version: v0.1.0

package turbo

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "github.com/senforsce/o/tr"
import tndrruntime "github.com/senforsce/tndr/runtime"

func actionTemplate(action string, target string) tndr.Component {
	return tndrruntime.GeneratedTemplate(func(tndr_7745c5c3_Input tndrruntime.GeneratedComponentInput) (tndr_7745c5c3_Err error) {
		tndr_7745c5c3_W, ctx := tndr_7745c5c3_Input.Writer, tndr_7745c5c3_Input.Context
		if tndr_7745c5c3_CtxErr := ctx.Err(); tndr_7745c5c3_CtxErr != nil {
			return tndr_7745c5c3_CtxErr
		}
		tndr_7745c5c3_Buffer, tndr_7745c5c3_IsBuffer := tndrruntime.GetBuffer(tndr_7745c5c3_W)
		if !tndr_7745c5c3_IsBuffer {
			defer func() {
				tndr_7745c5c3_BufErr := tndrruntime.ReleaseBuffer(tndr_7745c5c3_Buffer)
				if tndr_7745c5c3_Err == nil {
					tndr_7745c5c3_Err = tndr_7745c5c3_BufErr
				}
			}()
		}
		ctx = tndr.InitializeContext(ctx)
		tndr_7745c5c3_Var1 := tndr.GetChildren(ctx)
		if tndr_7745c5c3_Var1 == nil {
			tndr_7745c5c3_Var1 = tndr.NopComponent
		}
		ctx = tndr.ClearChildren(ctx)
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 1, "<turbo-stream action=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var2 string
		tndr_7745c5c3_Var2, tndr_7745c5c3_Err = tndr.JoinStringErrs(action)
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`turbo/stream.t1`), Line: 4, Col: 30}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var2))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 2, "\" target=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var3 string
		tndr_7745c5c3_Var3, tndr_7745c5c3_Err = tndr.JoinStringErrs(target)
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`turbo/stream.t1`), Line: 4, Col: 48}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var3))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 3, "\"><template id=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var4 string
		tndr_7745c5c3_Var4, tndr_7745c5c3_Err = tndr.JoinStringErrs(tr.Echo("test"))
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`turbo/stream.t1`), Line: 5, Col: 32}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var4))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 4, "\">")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndr_7745c5c3_Var1.Render(ctx, tndr_7745c5c3_Buffer)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 5, "</template></turbo-stream>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		return nil
	})
}

func removeTemplate(action string, target string) tndr.Component {
	return tndrruntime.GeneratedTemplate(func(tndr_7745c5c3_Input tndrruntime.GeneratedComponentInput) (tndr_7745c5c3_Err error) {
		tndr_7745c5c3_W, ctx := tndr_7745c5c3_Input.Writer, tndr_7745c5c3_Input.Context
		if tndr_7745c5c3_CtxErr := ctx.Err(); tndr_7745c5c3_CtxErr != nil {
			return tndr_7745c5c3_CtxErr
		}
		tndr_7745c5c3_Buffer, tndr_7745c5c3_IsBuffer := tndrruntime.GetBuffer(tndr_7745c5c3_W)
		if !tndr_7745c5c3_IsBuffer {
			defer func() {
				tndr_7745c5c3_BufErr := tndrruntime.ReleaseBuffer(tndr_7745c5c3_Buffer)
				if tndr_7745c5c3_Err == nil {
					tndr_7745c5c3_Err = tndr_7745c5c3_BufErr
				}
			}()
		}
		ctx = tndr.InitializeContext(ctx)
		tndr_7745c5c3_Var5 := tndr.GetChildren(ctx)
		if tndr_7745c5c3_Var5 == nil {
			tndr_7745c5c3_Var5 = tndr.NopComponent
		}
		ctx = tndr.ClearChildren(ctx)
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 6, "<turbo-stream action=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var6 string
		tndr_7745c5c3_Var6, tndr_7745c5c3_Err = tndr.JoinStringErrs(action)
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`turbo/stream.t1`), Line: 12, Col: 30}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var6))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 7, "\" target=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var7 string
		tndr_7745c5c3_Var7, tndr_7745c5c3_Err = tndr.JoinStringErrs(target)
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`turbo/stream.t1`), Line: 12, Col: 48}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var7))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 8, "\"></turbo-stream>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		return nil
	})
}

var _ = tndrruntime.GeneratedTemplate
