// Code generated by tndr - DO NOT EDIT.

// tndr: version: v0.1.0

package visualize

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "github.com/senforsce/o/tr"
import tndrruntime "github.com/senforsce/tndr/runtime"

func row() tndr.CSSClass {
	tndr_7745c5c3_CSSBuilder := tndrruntime.GetBuilder()
	tndr_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	tndr_7745c5c3_CSSID := tndr.CSSID(`row`, tndr_7745c5c3_CSSBuilder.String())
	return tndr.ComponentCSSClass{
		ID:    tndr_7745c5c3_CSSID,
		Class: tndr.SafeCSS(`.` + tndr_7745c5c3_CSSID + `{` + tndr_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func column() tndr.CSSClass {
	tndr_7745c5c3_CSSBuilder := tndrruntime.GetBuilder()
	tndr_7745c5c3_CSSBuilder.WriteString(`flex:50%;`)
	tndr_7745c5c3_CSSBuilder.WriteString(`overflow-y:scroll;`)
	tndr_7745c5c3_CSSBuilder.WriteString(`max-height:100vh;`)
	tndr_7745c5c3_CSSID := tndr.CSSID(`column`, tndr_7745c5c3_CSSBuilder.String())
	return tndr.ComponentCSSClass{
		ID:    tndr_7745c5c3_CSSID,
		Class: tndr.SafeCSS(`.` + tndr_7745c5c3_CSSID + `{` + tndr_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func code() tndr.CSSClass {
	tndr_7745c5c3_CSSBuilder := tndrruntime.GetBuilder()
	tndr_7745c5c3_CSSBuilder.WriteString(`font-family:monospace;`)
	tndr_7745c5c3_CSSID := tndr.CSSID(`code`, tndr_7745c5c3_CSSBuilder.String())
	return tndr.ComponentCSSClass{
		ID:    tndr_7745c5c3_CSSID,
		Class: tndr.SafeCSS(`.` + tndr_7745c5c3_CSSID + `{` + tndr_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func combine(tndrFileName string, left, right tndr.Component) tndr.Component {
	return tndrruntime.GeneratedTemplate(func(tndr_7745c5c3_Input tndrruntime.GeneratedComponentInput) (tndr_7745c5c3_Err error) {
		tndr_7745c5c3_W, ctx := tndr_7745c5c3_Input.Writer, tndr_7745c5c3_Input.Context
		if tndr_7745c5c3_CtxErr := ctx.Err(); tndr_7745c5c3_CtxErr != nil {
			return tndr_7745c5c3_CtxErr
		}
		tndr_7745c5c3_Buffer, tndr_7745c5c3_IsBuffer := tndrruntime.GetBuffer(tndr_7745c5c3_W)
		if !tndr_7745c5c3_IsBuffer {
			defer func() {
				tndr_7745c5c3_BufErr := tndrruntime.ReleaseBuffer(tndr_7745c5c3_Buffer)
				if tndr_7745c5c3_Err == nil {
					tndr_7745c5c3_Err = tndr_7745c5c3_BufErr
				}
			}()
		}
		ctx = tndr.InitializeContext(ctx)
		tndr_7745c5c3_Var1 := tndr.GetChildren(ctx)
		if tndr_7745c5c3_Var1 == nil {
			tndr_7745c5c3_Var1 = tndr.NopComponent
		}
		ctx = tndr.ClearChildren(ctx)
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 1, "<html><head><title>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var2 string
		tndr_7745c5c3_Var2, tndr_7745c5c3_Err = tndr.JoinStringErrs(tndrFileName)
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/visualize/sourcemapvisualisation.t1`), Line: 20, Col: 24}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var2))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 2, "- Source Map Visualisation</title><style type=\"text/css\">\n\t\t\t\t.mapped {\n\t\t\t\t\tbackground-color: green;\n\t\t\t\t}\n\t\t\t\t.highlighted {\n\t\t\t\t\tbackground-color: yellow;\n\t\t\t\t}\n\t\t\t</style></head><body><h1>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var3 string
		tndr_7745c5c3_Var3, tndr_7745c5c3_Err = tndr.JoinStringErrs(tndrFileName)
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/visualize/sourcemapvisualisation.t1`), Line: 31, Col: 21}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var3))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 3, "</h1>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var4 = []any{tndr.Classes(row())}
		tndr_7745c5c3_Err = tndr.RenderCSSItems(ctx, tndr_7745c5c3_Buffer, tndr_7745c5c3_Var4...)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 4, "<div class=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var5 string
		tndr_7745c5c3_Var5, tndr_7745c5c3_Err = tndr.JoinStringErrs(tndr.CSSClasses(tndr_7745c5c3_Var4).String())
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/visualize/sourcemapvisualisation.t1`), Line: 1, Col: 0}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var5))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 5, "\">")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var6 = []any{tndr.Classes(column(), code())}
		tndr_7745c5c3_Err = tndr.RenderCSSItems(ctx, tndr_7745c5c3_Buffer, tndr_7745c5c3_Var6...)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 6, "<div class=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var7 string
		tndr_7745c5c3_Var7, tndr_7745c5c3_Err = tndr.JoinStringErrs(tndr.CSSClasses(tndr_7745c5c3_Var6).String())
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/visualize/sourcemapvisualisation.t1`), Line: 1, Col: 0}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var7))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 7, "\">")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = left.Render(ctx, tndr_7745c5c3_Buffer)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 8, "</div>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var8 = []any{tndr.Classes(column(), code())}
		tndr_7745c5c3_Err = tndr.RenderCSSItems(ctx, tndr_7745c5c3_Buffer, tndr_7745c5c3_Var8...)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 9, "<div class=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var9 string
		tndr_7745c5c3_Var9, tndr_7745c5c3_Err = tndr.JoinStringErrs(tndr.CSSClasses(tndr_7745c5c3_Var8).String())
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/visualize/sourcemapvisualisation.t1`), Line: 1, Col: 0}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var9))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 10, "\">")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = right.Render(ctx, tndr_7745c5c3_Buffer)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 11, "</div></div></body></html>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		return nil
	})
}

func highlight(sourceId, targetId string) tndr.ComponentScript {
	return tndr.ComponentScript{
		Name: `__tndr_highlight_ae80`,
		Function: `function __tndr_highlight_ae80(sourceId, targetId){let items = document.getElementsByClassName(sourceId);
	for(let i = 0; i < items.length; i ++) {
		items[i].classList.add("highlighted");
	}
        items = document.getElementsByClassName(targetId);
	for(let i = 0; i < items.length; i ++) {
		items[i].classList.add("highlighted");
	}
}`,
		Call:       tndr.SafeScript(`__tndr_highlight_ae80`, sourceId, targetId),
		CallInline: tndr.SafeScriptInline(`__tndr_highlight_ae80`, sourceId, targetId),
	}
}

func removeHighlight(sourceId, targetId string) tndr.ComponentScript {
	return tndr.ComponentScript{
		Name: `__tndr_removeHighlight_58f2`,
		Function: `function __tndr_removeHighlight_58f2(sourceId, targetId){let items = document.getElementsByClassName(sourceId);
	for(let i = 0; i < items.length; i ++) {
		items[i].classList.remove("highlighted");
	}
        items = document.getElementsByClassName(targetId);
	for(let i = 0; i < items.length; i ++) {
		items[i].classList.remove("highlighted");
	}
}`,
		Call:       tndr.SafeScript(`__tndr_removeHighlight_58f2`, sourceId, targetId),
		CallInline: tndr.SafeScriptInline(`__tndr_removeHighlight_58f2`, sourceId, targetId),
	}
}

func mappedCharacter(s string, sourceID, targetID string) tndr.Component {
	return tndrruntime.GeneratedTemplate(func(tndr_7745c5c3_Input tndrruntime.GeneratedComponentInput) (tndr_7745c5c3_Err error) {
		tndr_7745c5c3_W, ctx := tndr_7745c5c3_Input.Writer, tndr_7745c5c3_Input.Context
		if tndr_7745c5c3_CtxErr := ctx.Err(); tndr_7745c5c3_CtxErr != nil {
			return tndr_7745c5c3_CtxErr
		}
		tndr_7745c5c3_Buffer, tndr_7745c5c3_IsBuffer := tndrruntime.GetBuffer(tndr_7745c5c3_W)
		if !tndr_7745c5c3_IsBuffer {
			defer func() {
				tndr_7745c5c3_BufErr := tndrruntime.ReleaseBuffer(tndr_7745c5c3_Buffer)
				if tndr_7745c5c3_Err == nil {
					tndr_7745c5c3_Err = tndr_7745c5c3_BufErr
				}
			}()
		}
		ctx = tndr.InitializeContext(ctx)
		tndr_7745c5c3_Var10 := tndr.GetChildren(ctx)
		if tndr_7745c5c3_Var10 == nil {
			tndr_7745c5c3_Var10 = tndr.NopComponent
		}
		ctx = tndr.ClearChildren(ctx)
		var tndr_7745c5c3_Var11 = []any{tndr.Classes(tndr.Class("mapped"), tndr.Class(sourceID), tndr.Class(targetID))}
		tndr_7745c5c3_Err = tndr.RenderCSSItems(ctx, tndr_7745c5c3_Buffer, tndr_7745c5c3_Var11...)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndr.RenderScriptItems(ctx, tndr_7745c5c3_Buffer, highlight(sourceID, targetID), removeHighlight(sourceID, targetID))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 12, "<span class=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var12 string
		tndr_7745c5c3_Var12, tndr_7745c5c3_Err = tndr.JoinStringErrs(tndr.CSSClasses(tndr_7745c5c3_Var11).String())
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/visualize/sourcemapvisualisation.t1`), Line: 1, Col: 0}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var12))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 13, "\" onMouseOver=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var13 tndr.ComponentScript = highlight(sourceID, targetID)
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr_7745c5c3_Var13.Call)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 14, "\" onMouseOut=\"")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var14 tndr.ComponentScript = removeHighlight(sourceID, targetID)
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr_7745c5c3_Var14.Call)
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 15, "\">")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		var tndr_7745c5c3_Var15 string
		tndr_7745c5c3_Var15, tndr_7745c5c3_Err = tndr.JoinStringErrs(s)
		if tndr_7745c5c3_Err != nil {
			return tndr.Error{Err: tndr_7745c5c3_Err, FileName: tr.Echo(`cmd/t1/visualize/sourcemapvisualisation.t1`), Line: 67, Col: 196}
		}
		_, tndr_7745c5c3_Err = tndr_7745c5c3_Buffer.WriteString(tndr.EscapeString(tndr_7745c5c3_Var15))
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		tndr_7745c5c3_Err = tndrruntime.WriteString(tndr_7745c5c3_Buffer, 16, "</span>")
		if tndr_7745c5c3_Err != nil {
			return tndr_7745c5c3_Err
		}
		return nil
	})
}

var _ = tndrruntime.GeneratedTemplate
